name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --workspace --all-targets --all-features --verbose -- -D warnings
    - name: Build no_std
      run: cargo build --workspace --no-default-features --verbose
    - name: Build std
      run: cargo build --workspace --all-features --verbose
    - name: Tests
      run: cargo test --workspace --all-features --verbose
